rabbitmq:
  user: rpc-user
  password: rpc-user
  host: 192.168.1.56
  port: 5672
  exchange: ""
  routingKeyPrefix: rpc.queue
  queuePrefix: rpc.queue
  replyQueuePrefix: rpc.reply
  rpcTimeout: 5000


